principals:
- name: admin-pod
  domain: admin-pod
  kind: curl
- name: auth
  domain: auth
  kind: json
- name: batch
  domain: batch
  kind: json
- name: batch-driver
  domain: batch-driver
  kind: json
- name: ci
  domain: ci
  kind: json
- name: notebook
  domain: notebook
  kind: json
- name: gateway
  domain: gateway
  unmanged: True
  kind: nginx
- name: router
  domain: router
  kind: nginx
- name: site
  domain: site
  kind: nginx
- name: scorecard
  domain: scorecard
  kind: json
- name: image-fetcher
  domain: image-fetcher
  kind: curl
- name: blog
  domain: blog
  kind: nginx
- name: router-resolver
  domain: router-resolver
  unmanged: True
  kind: json
- name: internal-gateway
  domain: internal-gateway
  unmanged: True
  kind: nginx
- name: batch-tests
  domain: batch-tests
  kind: json
- name: ci-tests
  domain: ci-tests
  kind: json
- name: query
  domain: query
  kind: json
- name: services-java-tests
  domain: services-java-tests
  kind: json
- name: query-tests
  domain: query-tests
  kind: json
