apiVersion: apps/v1
kind: Deployment
metadata:
  name: scorecard-deployment
  labels:
    app: scorecard
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: scorecard
  replicas: 1
  template:
    metadata:
      labels:
        app: scorecard
        hail.is/sha: "{{ code.sha }}"
    spec:
{% if deploy %}
      priorityClassName: production
{% endif %}
      nodeSelector:
        preemptible: "false"
      containers:
      - name: scorecard
        image: "{{ scorecard_image.image }}"
        env:
         - name: HAIL_DEPLOY_CONFIG_FILE
           value: /deploy-config/deploy-config.json
         - name: HAIL_DOMAIN
           value: "{{ global.domain }}"
        resources:
          requests:
            memory: "500M"
            cpu: "500m"
        ports:
        - containerPort: 5000
        volumeMounts:
          - mountPath: /secrets
            readOnly: true
            name: scorecard-github-access-token
          - name: session-secret-key
            mountPath: /session-secret-key
            readOnly: true
          - name: deploy-config
            mountPath: /deploy-config
            readOnly: true
        readinessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: scorecard-github-access-token
          secret:
            secretName: scorecard-github-access-token
        - name: session-secret-key
          secret:
            optional: false
            secretName: session-secret-key
        - name: deploy-config
          secret:
            optional: false
            secretName: deploy-config
---
apiVersion: v1
kind: Service
metadata:
  name: scorecard
  labels:
    app: scorecard
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: scorecard
