apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch2-driver
  labels:
    app: batch2-driver
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: batch2-driver
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: batch2-driver
        hail.is/sha: "{{ code.sha }}"
        grafanak8sapp: "true"
    spec:
      serviceAccountName: batch2
{% if deploy %}
      priorityClassName: production
{% endif %}
      containers:
      - name: batch2-driver
        image: {{ batch2_image.image }}
        command:
         - python3
         - -m
         - batch.driver
        resources:
          requests:
            memory: "1G"
            cpu: "1"
        env:
         - name: HAIL_DOMAIN
           value: "{{ global.domain }}"
         - name: HAIL_DEPLOY_CONFIG_FILE
           value: /deploy-config/deploy-config.json
         - name: BATCH_WORKER_IMAGE
           value: "{{ batch2_worker_image.image }}"
         - name: HAIL_DEFAULT_NAMESPACE
           value: "{{ default_ns.name }}"
         - name: HAIL_BATCH_PODS_NAMESPACE
           value: "{{ batch_pods_ns.name }}"
         - name: PROJECT
           value: "{{ global.project }}"
         - name: ZONE
           value: "{{ global.zone }}"
         - name: KUBERNETES_SERVER_URL
           value: "{{ global.k8s_server_url }}"
        ports:
         - containerPort: 5000
        volumeMounts:
         - name: deploy-config
           mountPath: /deploy-config
           readOnly: true
         - name: session-secret-key
           mountPath: /session-secret-key
           readOnly: true
         - name: sql-config
           mountPath: /sql-config
           readOnly: true
         - name: gsa-key
           mountPath: /batch-gsa-key
           readOnly: true
         - name: batch2-tokens
           mountPath: /user-tokens
           readOnly: true
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
       - name: deploy-config
         secret:
           optional: false
           secretName: deploy-config
       - name: session-secret-key
         secret:
           optional: false
           secretName: session-secret-key
       - name: sql-config
         secret:
           optional: false
           secretName: "{{ batch2_database.user_secret_name }}"
       - name: gsa-key
         secret:
           optional: false
           secretName: batch2-gsa-key
       - name: batch2-tokens
         secret:
           optional: false
           secretName: batch2-tokens
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch2
  labels:
    app: batch2
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: batch2
  replicas: 3
  template:
    metadata:
      labels:
        app: batch2
        hail.is/sha: "{{ code.sha }}"
        grafanak8sapp: "true"
    spec:
{% if deploy %}
      priorityClassName: production
{% endif %}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - auth
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: preemptible
                operator: In
                values:
                - "true"
      containers:
      - name: batch2
        image: {{ batch2_image.image }}
        command:
         - python3
         - -m
         - batch.front_end
        env:
         - name: HAIL_DOMAIN
           value: "{{ global.domain }}"
         - name: HAIL_DEPLOY_CONFIG_FILE
           value: /deploy-config/deploy-config.json
         - name: HAIL_DEFAULT_NAMESPACE
           value: "{{ default_ns.name }}"
         - name: HAIL_BATCH_PODS_NAMESPACE
           value: "{{ batch_pods_ns.name }}"
         - name: PROJECT
           value: "{{ global.project }}"
         - name: ZONE
           value: "{{ global.zone }}"
         - name: KUBERNETES_SERVER_URL
           value: "{{ global.k8s_server_url }}"
{% if not deploy %}
         - name: HAIL_BATCH_JOB_DEFAULT_CPU
           value: "0.1"
         - name: HAIL_BATCH_JOB_DEFAULT_MEMORY
           value: "375M"
{% endif %}
        ports:
         - containerPort: 5000
        resources:
          requests:
            memory: "250M"
            cpu: "100m"
          limits:
            memory: "1G"
            cpu: "1"
        volumeMounts:
         - name: deploy-config
           mountPath: /deploy-config
           readOnly: true
         - name: session-secret-key
           mountPath: /session-secret-key
           readOnly: true
         - name: sql-config
           mountPath: /sql-config
           readOnly: true
         - name: gsa-key
           mountPath: /batch-gsa-key
           readOnly: true
         - name: batch2-tokens
           mountPath: /user-tokens
           readOnly: true
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
       - name: deploy-config
         secret:
           optional: false
           secretName: deploy-config
       - name: session-secret-key
         secret:
           optional: false
           secretName: session-secret-key
       - name: sql-config
         secret:
           optional: false
           secretName: "{{ batch2_database.user_secret_name }}"
       - name: gsa-key
         secret:
           optional: false
           secretName: batch2-gsa-key
       - name: batch2-tokens
         secret:
           optional: false
           secretName: batch2-tokens
      tolerations:
       - key: preemptible
         value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: batch2
  labels:
    app: batch2
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: batch2
---
apiVersion: v1
kind: Service
metadata:
  name: batch2-driver
  labels:
    app: batch2-driver
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: batch2-driver
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: batch2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: batch2
  minReplicas: 3
  maxReplicas: 10
  metrics:
   - type: Resource
     resource:
       name: cpu
       targetAverageUtilization: 80
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: batch2
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: batch2
