kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: batch2
rules:
- apiGroups: [""]
  resources: ["secrets", "serviceaccounts"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: batch2
subjects:
- kind: ServiceAccount
  name: batch2
  namespace: {{ default_ns.name }}
roleRef:
  kind: Role
  name: batch2
  apiGroup: ""
