apiVersion: v1
kind: Pod
metadata:
  name: test-batch2
spec:
  containers:
  - name: test-batch2
    image: "{{ test_batch2_image.image }}"
    env:
     - name: POD_IP
       valueFrom:
         fieldRef:
           fieldPath: status.podIP
     - name: HAIL_DEPLOY_CONFIG_FILE
       value: /deploy-config/deploy-config.json
    volumeMounts:
      - mountPath: /deploy-config
        readOnly: true
        name: deploy-config
      - mountPath: /user-tokens
        readOnly: true
        name: test-tokens
  volumes:
    - name: deploy-config
      secret:
        secretName: deploy-config
    - name: test-tokens
      secret:
        secretName: test-tokens
  restartPolicy: Never
