apiVersion: v1
kind: Pod
metadata:
  name: test-batch2
spec:
  containers:
  - name: test-batch2
    image: "{{ test_batch2_image.image }}"
    env:
     - name: POD_IP
       valueFrom:
         fieldRef:
           fieldPath: status.podIP
     - name: HAIL_DEPLOY_CONFIG_FILE
       value: /deploy-config/deploy-config.json
     - name: HAIL_BASE_IMAGE
       value: {{ base_image.image }}
     - name: CI_UTILS_IMAGE
       value: {{ ci_utils_image.image }}
     - name: HAIL_BATCH_PODS_NAMESPACE
       value: {{ batch_pods_ns.name }}
    volumeMounts:
      - mountPath: /deploy-config
        readOnly: true
        name: deploy-config
      - mountPath: /user-tokens
        readOnly: true
        name: test-tokens
  volumes:
    - name: deploy-config
      secret:
        secretName: deploy-config
    - name: test-tokens
      secret:
        secretName: test-tokens
  restartPolicy: Never
