apiVersion: v1
kind: Pod
metadata:
  name: delete-batch-tables
spec:
  containers:
  - name: delete-batch-tables
    image: "{{ batch_tables_image.image }}"
    command:
     - /bin/bash
     - -c
     - |
       set -ex
       mysql --defaults-extra-file=/secrets/batch-admin/sql-config.cnf < ./delete-batch-tables.sql
    volumeMounts:
      - mountPath: /secrets/batch-admin
        readOnly: true
        name: batch-admin-secret
  volumes:
    - name: batch-admin-secret
      secret:
        secretName: "{{ batch_database.admin_secret_name }}"
  restartPolicy: Never
