apiVersion: v1
kind: ServiceAccount
metadata:
  name: batch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch
  labels:
    app: batch
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: batch
  replicas: 1
  template:
    metadata:
      labels:
        app: batch
        hail.is/sha: "{{ code.sha }}"
        grafanak8sapp: "true"
    spec:
      serviceAccountName: batch
{% if deploy %}
      priorityClassName: production
{% endif %}
      containers:
      - name: batch
        image: "{{ batch_image.image }}"
        resources:
          requests:
            memory: "1G"
            cpu: "1"
        env:
         - name: HAIL_DOMAIN
           value: "{{ global.domain }}"
         - name: HAIL_DEPLOY_CONFIG_FILE
           value: /deploy-config/deploy-config.json
         - name: HAIL_POD_NAMESPACE
           value: "{{ batch_pods_ns.name }}"
         - name: BATCH_IMAGE
           value: "{{ batch_image.image }}"
{% if deploy %}
         - name: HAIL_INSTANCE_ID
           value: cd50b95a89914efb897965a5e982a29d
{% endif %}
{% if not deploy %}
         - name: HAIL_BATCH_JOB_DEFAULT_CPU
           value: "0.1"
         - name: HAIL_BATCH_JOB_DEFAULT_MEMORY
           value: "375M"
{% endif %}
        ports:
         - containerPort: 5000
        volumeMounts:
         - name: deploy-config
           mountPath: /deploy-config
           readOnly: true
         - name: session-secret-key
           mountPath: /session-secret-key
           readOnly: true
         - name: batch-user-secret
           mountPath: /batch-user-secret
           readOnly: true
         - name: gsa-key
           mountPath: /batch-gsa-key
           readOnly: true
         - name: batch-tokens
           mountPath: /user-tokens
           readOnly: true
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
       - name: deploy-config
         secret:
           optional: false
           secretName: deploy-config
       - name: session-secret-key
         secret:
           optional: false
           secretName: session-secret-key
       - name: batch-user-secret
         secret:
           optional: false
           secretName: "{{ batch_database.user_secret_name }}"
       - name: gsa-key
         secret:
           optional: false
           secretName: batch-gsa-key
       - name: batch-tokens
         secret:
           optional: false
           secretName: batch-tokens
---
apiVersion: v1
kind: Service
metadata:
  name: batch
  labels:
    app: batch
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: batch
