apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-driver
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auth-driver
rules:
 - apiGroups: [""]
   resources: ["secrets"]
   verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auth-driver
subjects:
 - kind: ServiceAccount
   name: auth-driver
roleRef:
  kind: Role
  name: auth-driver
  apiGroup: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-driver
  labels:
    app: auth-driver
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: auth-driver
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth-driver
        hail.is/sha: "{{ code.sha }}"
    spec:
      serviceAccountName: auth-driver
{% if deploy %}
      priorityClassName: production
{% endif %}
      nodeSelector:
        preemptible: "true"
      tolerations:
       - key: preemptible
         value: "true"
      containers:
       - name: auth-driver
         image: "{{ auth_image.image }}"
         command:
          - "python3"
          - -m
          - auth.driver
         env:
          - name: HAIL_DEPLOY_CONFIG_FILE
            value: /deploy-config/deploy-config.json
          - name: HAIL_DOMAIN
            value: "{{ global.domain }}"
          - name: PROJECT
            value: "{{ global.project }}"
          - name: ZONE
            value: "{{ global.zone }}"
          - name: HAIL_DEFAULT_NAMESPACE
            value: "{{ default_ns.name }}"
          - name: HAIL_BATCH_PODS_NAMESPACE
            value: "{{ batch_pods_ns.name }}"
         resources:
           requests:
             memory: "250M"
             cpu: "100m"
           limits:
             memory: "1G"
             cpu: "1"
         volumeMounts:
          - name: deploy-config
            mountPath: /deploy-config
            readOnly: true
          - name: database-server-config
            mountPath: /database-server-config
            readOnly: true
          - name: sql-config
            mountPath: /sql-config
            readOnly: true
          - name: gsa-key
            mountPath: /gsa-key
            readOnly: true
         ports:
          - containerPort: 5000
      volumes:
       - name: deploy-config
         secret:
           secretName: deploy-config
       - name: database-server-config
         secret:
           secretName: database-server-config
       - name: sql-config
         secret:
           secretName: "{{ auth_database.user_secret_name }}"
       - name: gsa-key
         secret:
           secretName: auth-gsa-key
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 3
  template:
    metadata:
      labels:
        app: auth
        hail.is/sha: "{{ code.sha }}"
    spec:
{% if deploy %}
      priorityClassName: production
{% endif %}
      nodeSelector:
        preemptible: "true"
      tolerations:
       - key: preemptible
         value: "true"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - auth
              topologyKey: "kubernetes.io/hostname"
      containers:
       - name: auth
         image: "{{ auth_image.image }}"
         command:
          - "python3"
          - -m
          - auth
         env:
          - name: HAIL_DEPLOY_CONFIG_FILE
            value: /deploy-config/deploy-config.json
          - name: HAIL_DOMAIN
            value: "{{ global.domain }}"
          - name: PROJECT
            value: "{{ global.project }}"
          - name: ZONE
            value: "{{ global.zone }}"
          - name: HAIL_DEFAULT_NAMESPACE
            value: "{{ default_ns.name }}"
          - name: HAIL_BATCH_PODS_NAMESPACE
            value: "{{ batch_pods_ns.name }}"
         resources:
           requests:
             memory: "250M"
             cpu: "100m"
           limits:
             memory: "1G"
             cpu: "1"
         volumeMounts:
          - name: deploy-config
            mountPath: /deploy-config
            readOnly: true
          - name: auth-oauth2-client-secret
            mountPath: /auth-oauth2-client-secret
            readOnly: true
          - name: session-secret-key
            mountPath: /session-secret-key
            readOnly: true
          - name: sql-config
            mountPath: /sql-config
            readOnly: true
          - name: gsa-key
            mountPath: /gsa-key
            readOnly: true
          - name: ssl-config-auth
            mountPath: /ssl-config
            readOnly: true
         ports:
          - containerPort: 5000
         readinessProbe:
           tcpSocket:
             port: 5000
           initialDelaySeconds: 5
           periodSeconds: 5
      volumes:
       - name: deploy-config
         secret:
           secretName: deploy-config
       - name: auth-oauth2-client-secret
         secret:
           secretName: auth-oauth2-client-secret
       - name: session-secret-key
         secret:
           secretName: session-secret-key
       - name: sql-config
         secret:
           secretName: "{{ auth_database.user_secret_name }}"
       - name: gsa-key
         secret:
           secretName: auth-gsa-key
       - name: ssl-config-auth
         secret:
           optional: false
           secretName: ssl-config-auth
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: auth
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth
  minReplicas: 3
  maxReplicas: 10
  metrics:
   - type: Resource
     resource:
       name: cpu
       targetAverageUtilization: 80
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: auth
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: auth
