apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
  labels:
    app: site
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: site
  replicas: 3
  template:
    metadata:
      labels:
        app: site
        hail.is/sha: "{{ code.sha }}"
    spec:
{% if deploy %}
      priorityClassName: production
{% endif %}
      nodeSelector:
        preemptible: "true"
      tolerations:
       - key: preemptible
         value: "true"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - site
              topologyKey: "kubernetes.io/hostname"
      containers:
       - name: site
         image: "{{ site_image.image }}"
         resources:
           requests:
             memory: "250M"
             cpu: "100m"
           limits:
             memory: "1G"
             cpu: "1"
         ports:
          - containerPort: 443
         env:
          - name: HAIL_DOMAIN
            value: {{ global.domain }}
          - name: HAIL_DEFAULT_NAMESPACE
            value: {{ default_ns.name }}
         volumeMounts:
          - name: ssl-config-site
            mountPath: /ssl-config
            readOnly: true
         livenessProbe:
           tcpSocket:
             port: 443
           initialDelaySeconds: 5
           periodSeconds: 5
         readinessProbe:
           tcpSocket:
             port: 443
           initialDelaySeconds: 5
           periodSeconds: 5
      volumes:
       - name: ssl-config-site
         secret:
           optional: false
           secretName: ssl-config-site
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: site
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: site
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: site
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: site
