apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-pod
  template:
    metadata:
      labels:
        app: admin-pod
    spec:
      containers:
       - name: admin-pod
         command:
          - bash
          - -c
          - |
              ln -s /sql-config/sql-config.cnf $HOME/.my.cnf
              while true; do sleep 1000; done
         image: {{ service_base_image.image }}
         volumeMounts:
          - name: deploy-config
            mountPath: /deploy-config
            readOnly: true
          - name: sql-config
            mountPath: /sql-config
            readOnly: true
      volumes:
       - name: deploy-config
         secret:
           secretName: deploy-config
       - name: sql-config
         secret:
           secretName: database-server-config
