apiVersion: apps/v1
kind: Deployment
metadata:
  name: executors
  labels:
    app: executors
    hail.is/sha: "{{ code.sha }}"
spec:
  selector:
    matchLabels:
      app: executors
  replicas: 2
  template:
    metadata:
      labels:
        app: executors
        hail.is/sha: "{{ code.sha }}"
    spec:
{% if deploy %}
      priorityClassName: production
{% endif %}
      tolerations:
       - key: preemptible
         value: "true"
      containers:
       - name: executor
         image: "{{ hail_test_base_image.image }}"
         command:
          - /bin/bash
          - -c
          - |
            CLASSPATH="$SPARK_HOME/jars/*" java is.hail.scheduler.Executor scheduler.{{ default_ns.name }}.svc.cluster.local 1
         resources:
           requests:
             memory: "1G"
             cpu: "1"
