kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: query
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: query
subjects:
- kind: ServiceAccount
  name: query
  namespace: {{ default_ns.name }}
roleRef:
  kind: Role
  name: query
  apiGroup: rbac.authorization.k8s.io
