apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: infrastructure
value: 1000000
globalDefault: false
description: "For infrastructure like gateway."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: production
value: 900000
globalDefault: false
description: "For production services like apiserver, batch, etc."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: user
value: 500000
globalDefault: true
description: "For user activities like user batch jobs."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: test
value: 0
globalDefault: false
description: "For tests."
