apiVersion: v1
kind: Pod
metadata:
  name: test-ci
spec:
  containers:
  - name: test-ci
    image: "{{ test_ci_image.image }}"
    env:
     - name: HAIL_DEPLOY_CONFIG_FILE
       value: /deploy-config/deploy-config.json
     - name: ORGANIZATION
       value: "hail-ci-test"
     - name: REPO_NAME
       value: "ci-test-{{ create_ci_test_repo.token }}"
     - name: NAMESPACE
       value: "{{ default_ns.name }}"
    volumeMounts:
      - mountPath: /deploy-config
        readOnly: true
        name: deploy-config
      - mountPath: /secret/ci-secrets
        readOnly: true
        name: hail-ci-0-1-service-account-key
  volumes:
    - name: deploy-config
      secret:
        secretName: deploy-config
    - name: hail-ci-0-1-service-account-key
      secret:
        secretName: hail-ci-0-1-service-account-key
  restartPolicy: Never
